image: python:latest

stages:
  - test
  - deploy

before_script:
  - python -V
  - pip install jinja2 -U
  - pip install -U toml

test-build:
  script:
  - python build.py

pages:
  stage: deploy
  script:
  - python build.py
  artifacts:
    paths:
    - public
  only:
  - master
