image: python:latest

stages:
  - test
  - deploy

before_script:
  - python -V
  - pip install jinja2 -U
  - pip install -U toml

test-build:
  stage: test
  script:
  - python build.py

update-bot:
  stage: test
  only:
    refs:
    - schedules
  script:
  # ssh
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  # git
  - git config --global user.email "untzag@gmail.com"
  - git config --global user.name "bullocky"
  # run
  - python update_bot/main.py

pages:
  stage: deploy
  script:
  - python build.py
  artifacts:
    paths:
    - public
  only:
  - main
