model = "wl-motor"
description = "Single axis stepper motor drive built for the purpose of controlling white light delay in an OPA."
make = "wright"
daemons = ["wright-wl-motor"]

[links]
manufacturer = "https://github.com/wright-group/wl-motor"
