name = "ads1115"
description = "Sensor daemon for ADS1115 4-channel ADC."
traits = ["is-daemon", "uses-i2c"]

[links]
source = "https://gitlab.com/yaq/yaqd-ads1115"
bugtracker = "https://gitlab.com/yaq/yaqd-ads1115/-/issues"
reference = "http://www.ti.com/product/ADS1115"

[config]
fsr.type = "number"
fsr.default = 2.048
fsr.options = [6.144, 4.096, 2.048, 1.024, 0.512, 0.256]
rate.type = "number"
rate.default = 128
rate.options = [8, 16, 32, 64, 128, 250, 475, 860]
channels.type = "[string,...]"
channels.description = "List of strings containing one or two characters. Each string represents a particular conversion involving one or two ADC input pins. If there are two characters 'AB', the converted returned voltage will be A-B. If the is one character 'A', the returned voltage will be A-GND. Conversions are accomplished for each of the listed channels, in order, for each measurement. Valid strings: '01', '03', '13', '23', '0', '1', '2', '3'."
channels.default = ["0", "1", "2", "3"]
