name = "gpio-digital-output"
description = "Daemon for driving Rasperry Pi GPIO pin as digital output."
traits = ["has-position", "is-discrete"]

[links]
source = "https://gitlab.com/yaq/yaqd-rpi-gpio"
bugtracker = "https://gitlab.com/yaq/yaqd-rpi-gpio/-/issues"
manufacturer = "https://www.raspberrypi.org/"

[installation]
PyPI = "https://pypi.org/project/yaqd-rpi-gpio/"

[config]
index.type = "number"
index.description = "Index of digital output pin. This daemon uses broadcom (BCM) pin numbering, not physical (board) numbering."