name = "lightcon-topas4-motor"
description = """
Daemon for the LightConversion WinTOPAS4 motors.
"""
traits = ["has-limits", "is-homeable", "is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-lightcon/"
bugtracker = "https://gitlab.com/yaq/yaqd-lightcon/issues"
manufacturer = "http://topas4info.lightcon.com/"

[config]
motor_index.type = "Integer"
motor_index.default = 1
motor_index.description = "Motor index"
base_url.type = "String"
base_url.description = "URL for the TOPAS4 server directly controlling the motor"

[installation]
PyPI = "https://pypi.org/project/yaqd-lightcon"
