name = "mcp3428"
description = "Daemon to interface with MCP3428 four-channel analog to digital converter."
traits = ["is-sensor", "uses-i2c", "is-daemon"]

[links]
repository = "https://gitlab.com/yaq/yaqd-microchip"
bugtracker = "https://gitlab.com/yaq/yaqd-microchip/issues"
manufacturer = "https://www.microchip.com/wwwproducts/en/MCP3428"

[installation]
PyPI = "https://pypi.org/project/yaqd-microchip"

[state]
gain.type = "integer"
gain.options = [1, 2, 4, 8]
size.type = "integer"
size.options = [12, 14, 16]
