name = "micro-hr"
description = "Horiba Jobin-Yvon Micro-Hr monochromator."
traits = ["has-turret", "is-homeable", "has-limits", "is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-horiba"
bugtracker = "https://gitlab.com/yaq/yaqd-horiba/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-horiba/"

[config]
gratings.type = "[{'lines_per_mm': 'number'}, ...]"
make.default = "Horiba Jobin-Yvon"
model.default = "MicroHR"
