name = "newport-smc100"
description = """
Daemon for the Newport smc100-[CC|PP] controllers
"""
traits = ["has-limits", "is-homeable", "uses-uart", "is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-newport/"
bugtracker = "https://gitlab.com/yaq/yaqd-newport/issues"
manufacturer = "https://www.newport.com/f/smc100-single-axis-dc-or-stepper-motion-controller"

[config]
axis.type = "Integer"
axis.default = 1
axis.description = "Allows for daisy chained controllers"
units.type = "String"
units.default = "mm"
units.description = "Units for the motor attatched to the controller"

[state]
status.type = "String"
status.description = "Device status, translated into text from the Tell Status (TS) command."
error_code.type = "String"
error_code.description = "Four digit code describing error conditions in the Tell Status (TS) command."

[installation]
PyPI = "https://pypi.org/project/yaqd-newport"
