name = "seabreeze"
description = "Sensor daemon for Ocean Optics SeaBreeze spectrometers."
traits = ["is-sensor", "is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-seabreeze"
bugtracker = "https://gitlab.com/yaq/yaqd-seabreeze/-/issues"
manufacturer = "https://www.oceaninsight.com/products/spectrometers/"

[installation]
PyPI = "https://pypi.org/project/yaqd-seabreeze"

[config]
correct_dark_counts.type = "boolean"
correct_dark_counts.default = false
correct_nonlinearity.type = "boolean"
correct_nonlinearity.default = false

[state]
integration_time_micros.type = "number"
integration_time_micros.description = "Integration time for collecting pixels"

[method]  # optional

  [method.set_integration_time_micros]
  args.set_integration_time_micros.type = "number"
  description = "Set the integration time in microseconds."

  [method.get_integration_time_micros]
  returns = "number"
  description = "Get the integration time in microseconds."
