name = "wright-wl-motor"
description = "Single axis stepper motor drive built for the purpose of controlling white light delay in an OPA."
traits = ["is-homeable", "uses-uart", "is-daemon"]

[links]
source = "https://github.com/wright-group/wl-motor"
bugtracker = "https://github.com/wright-group/wl-motor/issues"
manufacturer = "https://github.com/wright-group/wl-motor/"

[installation]
PyPI = "https://pypi.org/project/yaqd-wright-wl-motor"

[config]
baudrate.default = 57600
