name = "has-position"
description = """
Daemons with this trait have one specific value that describes their current position.
This position can be set (using the set_position method).
In general, these daemons may not be able to reach exactly the set position.
The destination (get_destination) returns exactly the set position, while the position (get_position) returns the current actual position of the daemon.
These daemons should start motion and become busy when set_daemon is called.
They should release busy once they arrive as close as possible to the destination, and their position should not change until set_position is called again.
"""

[state]
position.type = "number"
destination.type = "number"

[method]

  [method.get_position]
  returns = "number"
  description = "Get current daemon position."

  [method.get_destination]
  returns = "number"
  description = "Get current daemon destination."

  [method.set_position]
  args.position.type = "number"
  description = "Give the daemon a new destination, and begin motion towards that destination."