name = "has-units"
description = "Daemons with this trait have a single 'units' field."

[method]

  [method.id]
  returns = "dictionary"
  description = "Must return value under key 'units'. Value can be String or None."
