name = "is-sensor"
description = """
Daemons with the is-sensor trait are capable of measuring some unknown quantities.
Sensor daemons may have multiple channels if a single measurement returns multiple values.
"""

[method]

  [method.measure]
  args.loop = "boolean"
  returns = "number"
  description = "Initiate a measurement. Returns integer, measurement ID."

  [method.get_channels]
  returns = "dictionary name: units"
  description = "Get current channels of sensor. Channels may change at runtime."

  [method.get_measured]
  returns = "dictionary name: value"
  description = "Get most recent measured value. Additional key of measurement ID."

  [method.stop_looping]
  description = "Stop looping measurement."